# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 17:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, db_index=True, max_length=24)),
                ('title', models.CharField(blank=True, db_index=True, max_length=64)),
                ('name', models.CharField(blank=True, db_index=True, max_length=24)),
                ('useforui', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DirectionPath',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, db_index=True)),
                ('direction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='DirectionStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, db_index=True)),
                ('stopid', models.CharField(blank=True, max_length=8)),
                ('direction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Direction')),
            ],
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.IntegerField(db_index=True, null=True)),
                ('line', models.CharField(max_length=8)),
                ('line_geom', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=100000)),
                ('direction', models.IntegerField(blank=True, db_index=True)),
                ('numtag', models.CharField(max_length=16)),
                ('tag', models.CharField(max_length=16)),
            ],
        ),
        migrations.CreateModel(
            name='Path',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True)),
                ('loc', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=100000)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True)),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('path', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Path')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(blank=True, max_length=5)),
                ('tag', models.CharField(blank=True, max_length=5)),
                ('numtag', models.CharField(blank=True, max_length=5)),
                ('title', models.CharField(blank=True, max_length=64)),
                ('color', models.TextField(blank=True)),
                ('oppositecolor', models.TextField(blank=True)),
                ('latmin', models.FloatField(blank=True)),
                ('latmax', models.FloatField(blank=True)),
                ('lonmin', models.FloatField(blank=True)),
                ('lonmax', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField(blank=True, db_index=True)),
                ('route', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.BigIntegerField(blank=True, db_index=True)),
                ('end_time', models.BigIntegerField(blank=True, db_index=True)),
                ('start_date', models.DateTimeField(blank=True, db_index=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True)),
                ('speed', models.FloatField(blank=True, db_index=True)),
                ('distance', models.FloatField(blank=True, db_index=True)),
                ('log', models.TextField(blank=True)),
                ('runlets', models.IntegerField(blank=True, db_index=True)),
                ('freq', models.IntegerField(blank=True, db_index=True)),
                ('direction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Direction')),
                ('route', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Runlet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat0', models.FloatField(blank=True, db_index=True)),
                ('lon0', models.FloatField(blank=True, db_index=True)),
                ('loc0', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=100000)),
                ('t0', models.IntegerField(blank=True, db_index=True)),
                ('latn', models.FloatField(blank=True, db_index=True)),
                ('lonn', models.FloatField(blank=True, db_index=True)),
                ('locn', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=100000)),
                ('tn', models.IntegerField(blank=True, db_index=True)),
                ('distance', models.FloatField(blank=True, db_index=True)),
                ('stop', models.TextField(blank=True)),
                ('stop_seq', models.IntegerField(blank=True)),
                ('path', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Path')),
                ('run', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Run')),
            ],
        ),
        migrations.CreateModel(
            name='Speed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(blank=True, db_index=True)),
                ('datype', models.IntegerField(blank=True, db_index=True)),
                ('speed', models.FloatField(blank=True, db_index=True)),
                ('min', models.FloatField(blank=True, db_index=True)),
                ('max', models.FloatField(blank=True, db_index=True)),
                ('navg', models.IntegerField(blank=True, db_index=True)),
                ('direction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Direction')),
                ('path', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Path')),
                ('route', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=8)),
                ('stop_id', models.CharField(blank=True, max_length=8)),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('loc', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=100000)),
                ('title', models.CharField(blank=True, db_index=True, max_length=64)),
                ('x', models.FloatField(blank=True)),
                ('y', models.FloatField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='StopId2Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(blank=True, max_length=8)),
                ('stop_id', models.CharField(blank=True, max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vid', models.TextField(blank=True)),
                ('lat', models.FloatField(blank=True)),
                ('lon', models.FloatField(blank=True)),
                ('loc', django.contrib.gis.db.models.fields.GeometryField(blank=True, srid=100000)),
                ('t', models.BigIntegerField(blank=True)),
                ('predictable', models.IntegerField(blank=True)),
                ('heading', models.IntegerField(blank=True)),
                ('speedkmhr', models.FloatField(blank=True)),
                ('leadingvehicleid', models.TextField(blank=True)),
                ('stop', models.TextField(blank=True)),
                ('stop_seq', models.IntegerField(blank=True)),
                ('direction', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Direction')),
                ('route', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Route')),
            ],
        ),
        migrations.AddField(
            model_name='run',
            name='vehicle',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Vehicle'),
        ),
        migrations.AddField(
            model_name='routestop',
            name='stop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Stop'),
        ),
        migrations.AddField(
            model_name='path',
            name='route',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Route'),
        ),
        migrations.AddField(
            model_name='directionstop',
            name='stop',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Stop'),
        ),
        migrations.AddField(
            model_name='directionpath',
            name='path',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Path'),
        ),
        migrations.AddField(
            model_name='direction',
            name='route',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='console.Route'),
        ),
    ]
