# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0005_auto_20180401_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runlet',
            name='stop_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='stop_seq',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
