# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 22:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('console', '0006_auto_20180401_1846'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='latlon',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
