# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='direction',
            name='name',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='direction',
            name='tag',
            field=models.CharField(blank=True, db_index=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='directionstop',
            name='stopid',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='line',
            name='line',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='route',
            name='line',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='route',
            name='numtag',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='route',
            name='tag',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='stop',
            name='tag',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='stopid2tag',
            name='stop_id',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AlterField(
            model_name='stopid2tag',
            name='tag',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
