# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-01 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('con', '0002_auto_20180401_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='predictable',
            field=models.BooleanField(),
        ),
    ]
